version: 2.1

jobs:
  build:
    working_directory: ~/algo-sorter-cci
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: install deps
          command: npm install --production=false
      - run:
          name: run tests
          command: npm test

workflows:
  algo-sorter-flow:
    jobs:
      - build
