version: 2.1

jobs:
  build:
    working_directory: ~/algo-sorter
    docker:       
      - image: circleci/node:lts      
    steps:
      - checkout
      - run: npm install
  test:
    working_directory: ~/algo-sorter
    docker:       
      - image: circleci/node:lts      
    steps:
      - checkout
      - run: npm test

workflows:
  algo-sorter-flow:
    jobs:
      - build
      - test:
          requires:
            - build
