version: 2.1

jobs:
  build:
    working_directory: ~/redux-async
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install deps
          command: npm install --production=false
      - run:
          name: test 
          command: npm test

workflows:
  algo-sorter-flow:
    jobs:
      - build
